"""add idempotency keys

Revision ID: 65a0d39488ca
Revises: 69858e972bcc
Create Date: 2026-05-13 02:05:21.355326

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '65a0d39488ca'
down_revision: Union[str, None] = '69858e972bcc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('idempotency_keys',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('key', sa.String(length=255), nullable=False),
    sa.Column('request_hash', sa.String(length=64), nullable=False),
    sa.Column('status', sa.Enum('processing', 'succeeded', 'failed', name='idempotency_status', native_enum=False), nullable=False),
    sa.Column('resource_type', sa.String(length=100), nullable=True),
    sa.Column('resource_id', sa.String(length=100), nullable=True),
    sa.Column('response_body', sa.JSON(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_idempotency_keys_expires_at'), 'idempotency_keys', ['expires_at'], unique=False)
    op.create_index(op.f('ix_idempotency_keys_key'), 'idempotency_keys', ['key'], unique=True)
    op.create_index(op.f('ix_idempotency_keys_resource_id'), 'idempotency_keys', ['resource_id'], unique=False)
    op.create_index(op.f('ix_idempotency_keys_resource_type'), 'idempotency_keys', ['resource_type'], unique=False)
    op.create_index(op.f('ix_idempotency_keys_status'), 'idempotency_keys', ['status'], unique=False)
    op.add_column('tickets', sa.Column('pending_action_id', sa.String(length=128), nullable=True))
    op.add_column('tickets', sa.Column('idempotency_key', sa.String(length=255), nullable=True))
    op.create_index(op.f('ix_tickets_idempotency_key'), 'tickets', ['idempotency_key'], unique=True)
    op.create_index(op.f('ix_tickets_pending_action_id'), 'tickets', ['pending_action_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tickets_pending_action_id'), table_name='tickets')
    op.drop_index(op.f('ix_tickets_idempotency_key'), table_name='tickets')
    op.drop_column('tickets', 'idempotency_key')
    op.drop_column('tickets', 'pending_action_id')
    op.drop_index(op.f('ix_idempotency_keys_status'), table_name='idempotency_keys')
    op.drop_index(op.f('ix_idempotency_keys_resource_type'), table_name='idempotency_keys')
    op.drop_index(op.f('ix_idempotency_keys_resource_id'), table_name='idempotency_keys')
    op.drop_index(op.f('ix_idempotency_keys_key'), table_name='idempotency_keys')
    op.drop_index(op.f('ix_idempotency_keys_expires_at'), table_name='idempotency_keys')
    op.drop_table('idempotency_keys')
    # ### end Alembic commands ###
