"""add ticket status transitions

Revision ID: cb17fcf166b8
Revises: d5db209da506
Create Date: 2026-05-15 06:58:24.846510

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'cb17fcf166b8'
down_revision: Union[str, None] = 'd5db209da506'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ticket_status_transitions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('ticket_id', sa.Uuid(), nullable=False),
    sa.Column('from_status', sa.Enum('open', 'processing', 'resolved', 'closed', 'cancelled', name='ticket_transition_from_status', native_enum=False), nullable=False),
    sa.Column('to_status', sa.Enum('open', 'processing', 'resolved', 'closed', 'cancelled', name='ticket_transition_to_status', native_enum=False), nullable=False),
    sa.Column('operator_id', sa.Uuid(), nullable=True),
    sa.Column('operator_role', sa.Enum('admin', 'hr', 'employee', name='ticket_transition_operator_role', native_enum=False), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['operator_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ticket_status_transitions_operator_id'), 'ticket_status_transitions', ['operator_id'], unique=False)
    op.create_index(op.f('ix_ticket_status_transitions_ticket_id'), 'ticket_status_transitions', ['ticket_id'], unique=False)
    op.alter_column('agent_tool_calls', 'trace_id',
               existing_type=sa.VARCHAR(length=128),
               comment=None,
               existing_comment='全局链路ID，用于全流程问题排查',
               existing_nullable=False)
    op.alter_column('agent_tool_calls', 'tool_call_id',
               existing_type=sa.VARCHAR(length=128),
               comment=None,
               existing_comment='Agent工具调用唯一ID',
               existing_nullable=False)
    op.alter_column('agent_tool_calls', 'external_session_id',
               existing_type=sa.VARCHAR(length=128),
               comment=None,
               existing_comment='外部会话唯一标识',
               existing_nullable=False)
    op.alter_column('agent_tool_calls', 'pending_action_id',
               existing_type=sa.VARCHAR(length=128),
               comment=None,
               existing_comment='关联的PendingAction ID',
               existing_nullable=False)
    op.alter_column('agent_tool_calls', 'tool_name',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='工具名称，默认创建HR工单',
               existing_nullable=False)
    op.alter_column('agent_tool_calls', 'request_payload',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment=None,
               existing_comment='工具请求参数JSON快照',
               existing_nullable=True)
    op.alter_column('agent_tool_calls', 'response_payload',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment=None,
               existing_comment='工具响应结果JSON快照',
               existing_nullable=True)
    op.alter_column('agent_tool_calls', 'status',
               existing_type=sa.VARCHAR(length=9),
               comment=None,
               existing_comment='工具调用状态：已接收/成功/失败/重复/冲突',
               existing_nullable=False)
    op.alter_column('agent_tool_calls', 'error_code',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='错误码，调用失败时使用',
               existing_nullable=True)
    op.alter_column('agent_tool_calls', 'error_message',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='错误详情信息',
               existing_nullable=True)
    op.alter_column('agent_tool_calls', 'latency_ms',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='接口耗时（毫秒）',
               existing_nullable=True)
    op.alter_column('agent_tool_calls', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='创建时间',
               existing_nullable=False)
    op.alter_column('agent_tool_calls', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='更新时间',
               existing_nullable=False)
    op.alter_column('pending_action_executions', 'external_session_id',
               existing_type=sa.VARCHAR(length=128),
               comment=None,
               existing_comment='外部会话ID',
               existing_nullable=False)
    op.alter_column('pending_action_executions', 'pending_action_id',
               existing_type=sa.VARCHAR(length=128),
               comment=None,
               existing_comment='待执行动作ID',
               existing_nullable=False)
    op.alter_column('pending_action_executions', 'idempotency_key',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='幂等键，防重复执行',
               existing_nullable=False)
    op.alter_column('pending_action_executions', 'action_type',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='动作类型',
               existing_nullable=False)
    op.alter_column('pending_action_executions', 'status',
               existing_type=sa.VARCHAR(length=19),
               comment=None,
               existing_comment='动作执行状态',
               existing_nullable=False)
    op.alter_column('pending_action_executions', 'confirmed_by_external',
               existing_type=sa.VARCHAR(length=128),
               comment=None,
               existing_comment='外部确认人ID',
               existing_nullable=True)
    op.alter_column('pending_action_executions', 'confirmed_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='人工确认时间',
               existing_nullable=True)
    op.alter_column('pending_action_executions', 'executed_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='动作执行时间',
               existing_nullable=True)
    op.alter_column('pending_action_executions', 'result_resource_type',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='结果资源类型',
               existing_nullable=True)
    op.alter_column('pending_action_executions', 'result_resource_id',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='结果资源ID',
               existing_nullable=True)
    op.alter_column('pending_action_executions', 'error_code',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='错误码',
               existing_nullable=True)
    op.alter_column('pending_action_executions', 'error_message',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='错误信息',
               existing_nullable=True)
    op.alter_column('pending_action_executions', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='创建时间',
               existing_nullable=False)
    op.alter_column('pending_action_executions', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='更新时间',
               existing_nullable=False)
    op.alter_column('ticket_policy_references', 'ticket_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='关联的工单ID',
               existing_nullable=False)
    op.alter_column('ticket_policy_references', 'external_session_id',
               existing_type=sa.VARCHAR(length=128),
               comment=None,
               existing_comment='外部会话ID',
               existing_nullable=True)
    op.alter_column('ticket_policy_references', 'pending_action_id',
               existing_type=sa.VARCHAR(length=128),
               comment=None,
               existing_comment='关联的PendingAction ID',
               existing_nullable=True)
    op.alter_column('ticket_policy_references', 'rag_query',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='RAG检索的用户问题',
               existing_nullable=True)
    op.alter_column('ticket_policy_references', 'rag_answer_snapshot',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='RAG回答快照（存档）',
               existing_nullable=True)
    op.alter_column('ticket_policy_references', 'document_id',
               existing_type=sa.VARCHAR(length=128),
               comment=None,
               existing_comment='知识库文档ID',
               existing_nullable=True)
    op.alter_column('ticket_policy_references', 'document_name',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='文档名称',
               existing_nullable=True)
    op.alter_column('ticket_policy_references', 'chunk_id',
               existing_type=sa.VARCHAR(length=128),
               comment=None,
               existing_comment='文档切片ID',
               existing_nullable=True)
    op.alter_column('ticket_policy_references', 'breadcrumb',
               existing_type=sa.VARCHAR(length=500),
               comment=None,
               existing_comment='文档目录路径',
               existing_nullable=True)
    op.alter_column('ticket_policy_references', 'page_number',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='文档页码',
               existing_nullable=True)
    op.alter_column('ticket_policy_references', 'retrieval_score',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='检索匹配度分数',
               existing_nullable=True)
    op.alter_column('ticket_policy_references', 'content_snapshot',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='制度条款原文快照',
               existing_nullable=True)
    op.alter_column('ticket_policy_references', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='创建时间',
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ticket_policy_references', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='创建时间',
               existing_nullable=False)
    op.alter_column('ticket_policy_references', 'content_snapshot',
               existing_type=sa.TEXT(),
               comment='制度条款原文快照',
               existing_nullable=True)
    op.alter_column('ticket_policy_references', 'retrieval_score',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='检索匹配度分数',
               existing_nullable=True)
    op.alter_column('ticket_policy_references', 'page_number',
               existing_type=sa.INTEGER(),
               comment='文档页码',
               existing_nullable=True)
    op.alter_column('ticket_policy_references', 'breadcrumb',
               existing_type=sa.VARCHAR(length=500),
               comment='文档目录路径',
               existing_nullable=True)
    op.alter_column('ticket_policy_references', 'chunk_id',
               existing_type=sa.VARCHAR(length=128),
               comment='文档切片ID',
               existing_nullable=True)
    op.alter_column('ticket_policy_references', 'document_name',
               existing_type=sa.VARCHAR(length=255),
               comment='文档名称',
               existing_nullable=True)
    op.alter_column('ticket_policy_references', 'document_id',
               existing_type=sa.VARCHAR(length=128),
               comment='知识库文档ID',
               existing_nullable=True)
    op.alter_column('ticket_policy_references', 'rag_answer_snapshot',
               existing_type=sa.TEXT(),
               comment='RAG回答快照（存档）',
               existing_nullable=True)
    op.alter_column('ticket_policy_references', 'rag_query',
               existing_type=sa.TEXT(),
               comment='RAG检索的用户问题',
               existing_nullable=True)
    op.alter_column('ticket_policy_references', 'pending_action_id',
               existing_type=sa.VARCHAR(length=128),
               comment='关联的PendingAction ID',
               existing_nullable=True)
    op.alter_column('ticket_policy_references', 'external_session_id',
               existing_type=sa.VARCHAR(length=128),
               comment='外部会话ID',
               existing_nullable=True)
    op.alter_column('ticket_policy_references', 'ticket_id',
               existing_type=sa.UUID(),
               comment='关联的工单ID',
               existing_nullable=False)
    op.alter_column('pending_action_executions', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='更新时间',
               existing_nullable=False)
    op.alter_column('pending_action_executions', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='创建时间',
               existing_nullable=False)
    op.alter_column('pending_action_executions', 'error_message',
               existing_type=sa.TEXT(),
               comment='错误信息',
               existing_nullable=True)
    op.alter_column('pending_action_executions', 'error_code',
               existing_type=sa.VARCHAR(length=100),
               comment='错误码',
               existing_nullable=True)
    op.alter_column('pending_action_executions', 'result_resource_id',
               existing_type=sa.VARCHAR(length=100),
               comment='结果资源ID',
               existing_nullable=True)
    op.alter_column('pending_action_executions', 'result_resource_type',
               existing_type=sa.VARCHAR(length=100),
               comment='结果资源类型',
               existing_nullable=True)
    op.alter_column('pending_action_executions', 'executed_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='动作执行时间',
               existing_nullable=True)
    op.alter_column('pending_action_executions', 'confirmed_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='人工确认时间',
               existing_nullable=True)
    op.alter_column('pending_action_executions', 'confirmed_by_external',
               existing_type=sa.VARCHAR(length=128),
               comment='外部确认人ID',
               existing_nullable=True)
    op.alter_column('pending_action_executions', 'status',
               existing_type=sa.VARCHAR(length=19),
               comment='动作执行状态',
               existing_nullable=False)
    op.alter_column('pending_action_executions', 'action_type',
               existing_type=sa.VARCHAR(length=100),
               comment='动作类型',
               existing_nullable=False)
    op.alter_column('pending_action_executions', 'idempotency_key',
               existing_type=sa.VARCHAR(length=255),
               comment='幂等键，防重复执行',
               existing_nullable=False)
    op.alter_column('pending_action_executions', 'pending_action_id',
               existing_type=sa.VARCHAR(length=128),
               comment='待执行动作ID',
               existing_nullable=False)
    op.alter_column('pending_action_executions', 'external_session_id',
               existing_type=sa.VARCHAR(length=128),
               comment='外部会话ID',
               existing_nullable=False)
    op.alter_column('agent_tool_calls', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='更新时间',
               existing_nullable=False)
    op.alter_column('agent_tool_calls', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='创建时间',
               existing_nullable=False)
    op.alter_column('agent_tool_calls', 'latency_ms',
               existing_type=sa.INTEGER(),
               comment='接口耗时（毫秒）',
               existing_nullable=True)
    op.alter_column('agent_tool_calls', 'error_message',
               existing_type=sa.TEXT(),
               comment='错误详情信息',
               existing_nullable=True)
    op.alter_column('agent_tool_calls', 'error_code',
               existing_type=sa.VARCHAR(length=100),
               comment='错误码，调用失败时使用',
               existing_nullable=True)
    op.alter_column('agent_tool_calls', 'status',
               existing_type=sa.VARCHAR(length=9),
               comment='工具调用状态：已接收/成功/失败/重复/冲突',
               existing_nullable=False)
    op.alter_column('agent_tool_calls', 'response_payload',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment='工具响应结果JSON快照',
               existing_nullable=True)
    op.alter_column('agent_tool_calls', 'request_payload',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment='工具请求参数JSON快照',
               existing_nullable=True)
    op.alter_column('agent_tool_calls', 'tool_name',
               existing_type=sa.VARCHAR(length=100),
               comment='工具名称，默认创建HR工单',
               existing_nullable=False)
    op.alter_column('agent_tool_calls', 'pending_action_id',
               existing_type=sa.VARCHAR(length=128),
               comment='关联的PendingAction ID',
               existing_nullable=False)
    op.alter_column('agent_tool_calls', 'external_session_id',
               existing_type=sa.VARCHAR(length=128),
               comment='外部会话唯一标识',
               existing_nullable=False)
    op.alter_column('agent_tool_calls', 'tool_call_id',
               existing_type=sa.VARCHAR(length=128),
               comment='Agent工具调用唯一ID',
               existing_nullable=False)
    op.alter_column('agent_tool_calls', 'trace_id',
               existing_type=sa.VARCHAR(length=128),
               comment='全局链路ID，用于全流程问题排查',
               existing_nullable=False)
    op.drop_index(op.f('ix_ticket_status_transitions_ticket_id'), table_name='ticket_status_transitions')
    op.drop_index(op.f('ix_ticket_status_transitions_operator_id'), table_name='ticket_status_transitions')
    op.drop_table('ticket_status_transitions')
    # ### end Alembic commands ###
