"""add agent trace and rag evidence

Revision ID: d5db209da506
Revises: 65a0d39488ca
Create Date: 2026-05-15 05:26:16.370314

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd5db209da506'
down_revision: Union[str, None] = '65a0d39488ca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_tool_calls',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('trace_id', sa.String(length=128), nullable=False, comment='全局链路ID，用于全流程问题排查'),
    sa.Column('tool_call_id', sa.String(length=128), nullable=False, comment='Agent工具调用唯一ID'),
    sa.Column('external_session_id', sa.String(length=128), nullable=False, comment='外部会话唯一标识'),
    sa.Column('pending_action_id', sa.String(length=128), nullable=False, comment='关联的PendingAction ID'),
    sa.Column('tool_name', sa.String(length=100), nullable=False, comment='工具名称，默认创建HR工单'),
    sa.Column('request_payload', sa.JSON(), nullable=True, comment='工具请求参数JSON快照'),
    sa.Column('response_payload', sa.JSON(), nullable=True, comment='工具响应结果JSON快照'),
    sa.Column('status', sa.Enum('received', 'succeeded', 'failed', 'replayed', 'conflict', name='agent_tool_call_status', native_enum=False), nullable=False, comment='工具调用状态：已接收/成功/失败/重复/冲突'),
    sa.Column('error_code', sa.String(length=100), nullable=True, comment='错误码，调用失败时使用'),
    sa.Column('error_message', sa.Text(), nullable=True, comment='错误详情信息'),
    sa.Column('latency_ms', sa.Integer(), nullable=True, comment='接口耗时（毫秒）'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='更新时间'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_tool_calls_external_session_id'), 'agent_tool_calls', ['external_session_id'], unique=False)
    op.create_index(op.f('ix_agent_tool_calls_pending_action_id'), 'agent_tool_calls', ['pending_action_id'], unique=False)
    op.create_index(op.f('ix_agent_tool_calls_status'), 'agent_tool_calls', ['status'], unique=False)
    op.create_index(op.f('ix_agent_tool_calls_tool_call_id'), 'agent_tool_calls', ['tool_call_id'], unique=False)
    op.create_index(op.f('ix_agent_tool_calls_trace_id'), 'agent_tool_calls', ['trace_id'], unique=False)
    op.create_table('pending_action_executions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('external_session_id', sa.String(length=128), nullable=False, comment='外部会话ID'),
    sa.Column('pending_action_id', sa.String(length=128), nullable=False, comment='待执行动作ID'),
    sa.Column('idempotency_key', sa.String(length=255), nullable=False, comment='幂等键，防重复执行'),
    sa.Column('action_type', sa.String(length=100), nullable=False, comment='动作类型'),
    sa.Column('status', sa.Enum('received', 'succeeded', 'failed', 'idempotent_replayed', 'conflict', name='pending_action_execution_status', native_enum=False), nullable=False, comment='动作执行状态'),
    sa.Column('confirmed_by_external', sa.String(length=128), nullable=True, comment='外部确认人ID'),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True, comment='人工确认时间'),
    sa.Column('executed_at', sa.DateTime(timezone=True), nullable=True, comment='动作执行时间'),
    sa.Column('result_resource_type', sa.String(length=100), nullable=True, comment='结果资源类型'),
    sa.Column('result_resource_id', sa.String(length=100), nullable=True, comment='结果资源ID'),
    sa.Column('error_code', sa.String(length=100), nullable=True, comment='错误码'),
    sa.Column('error_message', sa.Text(), nullable=True, comment='错误信息'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='更新时间'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pending_action_executions_external_session_id'), 'pending_action_executions', ['external_session_id'], unique=False)
    op.create_index(op.f('ix_pending_action_executions_idempotency_key'), 'pending_action_executions', ['idempotency_key'], unique=False)
    op.create_index(op.f('ix_pending_action_executions_pending_action_id'), 'pending_action_executions', ['pending_action_id'], unique=False)
    op.create_index(op.f('ix_pending_action_executions_result_resource_id'), 'pending_action_executions', ['result_resource_id'], unique=False)
    op.create_index(op.f('ix_pending_action_executions_result_resource_type'), 'pending_action_executions', ['result_resource_type'], unique=False)
    op.create_index(op.f('ix_pending_action_executions_status'), 'pending_action_executions', ['status'], unique=False)
    op.create_table('ticket_policy_references',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('ticket_id', sa.Uuid(), nullable=False, comment='关联的工单ID'),
    sa.Column('external_session_id', sa.String(length=128), nullable=True, comment='外部会话ID'),
    sa.Column('pending_action_id', sa.String(length=128), nullable=True, comment='关联的PendingAction ID'),
    sa.Column('rag_query', sa.Text(), nullable=True, comment='RAG检索的用户问题'),
    sa.Column('rag_answer_snapshot', sa.Text(), nullable=True, comment='RAG回答快照（存档）'),
    sa.Column('document_id', sa.String(length=128), nullable=True, comment='知识库文档ID'),
    sa.Column('document_name', sa.String(length=255), nullable=True, comment='文档名称'),
    sa.Column('chunk_id', sa.String(length=128), nullable=True, comment='文档切片ID'),
    sa.Column('breadcrumb', sa.String(length=500), nullable=True, comment='文档目录路径'),
    sa.Column('page_number', sa.Integer(), nullable=True, comment='文档页码'),
    sa.Column('retrieval_score', sa.Float(), nullable=True, comment='检索匹配度分数'),
    sa.Column('content_snapshot', sa.Text(), nullable=True, comment='制度条款原文快照'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='创建时间'),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ticket_policy_references_chunk_id'), 'ticket_policy_references', ['chunk_id'], unique=False)
    op.create_index(op.f('ix_ticket_policy_references_document_id'), 'ticket_policy_references', ['document_id'], unique=False)
    op.create_index(op.f('ix_ticket_policy_references_external_session_id'), 'ticket_policy_references', ['external_session_id'], unique=False)
    op.create_index(op.f('ix_ticket_policy_references_pending_action_id'), 'ticket_policy_references', ['pending_action_id'], unique=False)
    op.create_index(op.f('ix_ticket_policy_references_ticket_id'), 'ticket_policy_references', ['ticket_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ticket_policy_references_ticket_id'), table_name='ticket_policy_references')
    op.drop_index(op.f('ix_ticket_policy_references_pending_action_id'), table_name='ticket_policy_references')
    op.drop_index(op.f('ix_ticket_policy_references_external_session_id'), table_name='ticket_policy_references')
    op.drop_index(op.f('ix_ticket_policy_references_document_id'), table_name='ticket_policy_references')
    op.drop_index(op.f('ix_ticket_policy_references_chunk_id'), table_name='ticket_policy_references')
    op.drop_table('ticket_policy_references')
    op.drop_index(op.f('ix_pending_action_executions_status'), table_name='pending_action_executions')
    op.drop_index(op.f('ix_pending_action_executions_result_resource_type'), table_name='pending_action_executions')
    op.drop_index(op.f('ix_pending_action_executions_result_resource_id'), table_name='pending_action_executions')
    op.drop_index(op.f('ix_pending_action_executions_pending_action_id'), table_name='pending_action_executions')
    op.drop_index(op.f('ix_pending_action_executions_idempotency_key'), table_name='pending_action_executions')
    op.drop_index(op.f('ix_pending_action_executions_external_session_id'), table_name='pending_action_executions')
    op.drop_table('pending_action_executions')
    op.drop_index(op.f('ix_agent_tool_calls_trace_id'), table_name='agent_tool_calls')
    op.drop_index(op.f('ix_agent_tool_calls_tool_call_id'), table_name='agent_tool_calls')
    op.drop_index(op.f('ix_agent_tool_calls_status'), table_name='agent_tool_calls')
    op.drop_index(op.f('ix_agent_tool_calls_pending_action_id'), table_name='agent_tool_calls')
    op.drop_index(op.f('ix_agent_tool_calls_external_session_id'), table_name='agent_tool_calls')
    op.drop_table('agent_tool_calls')
    # ### end Alembic commands ###
